spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_sys_db?createDatabaseIfNotExist=true
    username: root
    password: Dinesh@12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
